config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin", to: 'devise/sessions#new'
    delete "signout", to: 'devise/sessions#destroy'
    get "signup", to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'
  # get 'users/:username', to: 'users#show', as: 'user'
  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  resources :items do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end

  resources :tweets

  # ActiveAdmin.routes(self)
  # devise_for :users
  # as :user do
  #   get "signin", to: 'devise/sessions#new'
  #   delete "signout", to: 'devise/sessions#destroy'
  #   get "signup", to: 'devise/registrations#new'
  # end
  # get 'pages/home'
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact_us', to: 'pages#contact_us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 200 }

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/tweets_controller.rb
# class TweetsController < ApplicationController
#   before_action :set_tweet, only: [:show, :edit, :update, :destroy]
#
#   # GET /tweets
#   # GET /tweets.json
#   def index
#     @tweets = Tweet.all
#   end
#
#   # GET /tweets/1
#   # GET /tweets/1.json
#   def show
#   end
#
#   # GET /tweets/new
#   def new
#     @tweet = Tweet.new
#   end
#
#   # GET /tweets/1/edit
#   def edit
#   end
#
#   # POST /tweets
#   # POST /tweets.json
#   def create
#     @tweet = Tweet.new(tweet_params)
#
#     respond_to do |format|
#       if @tweet.save
#         format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
#         format.json { render :show, status: :created, location: @tweet }
#       else
#         format.html { render :new }
#         format.json { render json: @tweet.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # PATCH/PUT /tweets/1
#   # PATCH/PUT /tweets/1.json
#   def update
#     respond_to do |format|
#       if @tweet.update(tweet_params)
#         format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
#         format.json { render :show, status: :ok, location: @tweet }
#       else
#         format.html { render :edit }
#         format.json { render json: @tweet.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # DELETE /tweets/1
#   # DELETE /tweets/1.json
#   def destroy
#     @tweet.destroy
#     respond_to do |format|
#       format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end
#
#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_tweet
#       @tweet = Tweet.find(params[:id])
#     end
#
#     # Never trust parameters from the scary internet, only allow the white list through.
#     def tweet_params
#       params.require(:tweet).permit(:user_id, :content)
#     end
# end


class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    # @tweet = Tweet.new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    # @tweet = Tweet.find(params[:id])
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    # @tweet = Tweet.new(tweet_params)
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    # @tweet = Tweet.find(params[:id])
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    # @tweet = Tweet.find(params[:id])
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      # params.require(:tweet).permit(:user_id, :content)
      params.require(:tweet).permit(:content, :image)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, html: {multipart: true}) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>
      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
    <%= form.submit 'Submit', class: "btn btn-primary" %>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">
  <h1>Editing Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Show', @tweet %> |
  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-4">
        <% if user_signed_in? %>
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Your Account</h5>
              <p class="card-text"><%= link_to current_user.username, user_path(current_user.username) %></p>
            </div>
          </div>
        <% else %>
          <p class="card-text"><%= link_to "Sign up now to be able to start posting!", signup_path %></p>
        <% end %>
      </div>
      <div class="col-md-8">
        <% if user_signed_in? %>
          <%= link_to 'New Tweet', new_tweet_path %>
        <% end %>
          <ul class="list-group">
              <% @tweets.each do |tweet| %>
                  <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
                    <h5><%= tweet.user.username %></h5>
                    <% if tweet.image.present? %>
                      <%= link_to tweet.image.url do %>
                        <%= image_tag tweet.image.url, class: "img-fluid" %>
                      <% end %>
                    <% end %>
                    <p><%= tweet.content %></p>
                      <small>
                        <% if tweet.user == current_user %>
                          <%= link_to 'Edit', edit_tweet_path(tweet) %>
                          <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
                        <% end %>
                      </small>
                  <% end %>
              <% end %>
          </ul>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <h1>New Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card card-block">
        <h4 class="card-title"><%= link_to @tweet.user.username, user_path(@tweet.user.username) %></h4>
        <%= link_to @tweet.image.url do %>
          <%= image_tag @tweet.image.url, class: "img-fluid" %>
        <% end %>
        <p class="card-text"><%= @tweet.content %></p>
          <% if @tweet.user == current_user %>
           <%= link_to 'Edit', edit_tweet_path(@tweet), class: "card-link" %>
           <%= link_to 'Delete', @tweet, method: :delete, class: "card-link" %>
          <% end %>
           <%= link_to 'Back', tweets_path, class: "card-link" %>
      </div>
    </div>
  </div>
</div>