config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin", to: 'devise/sessions#new'
    delete "signout", to: 'devise/sessions#destroy'
    get "signup", to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'
  # get 'users/:username', to: 'users#show', as: 'user'
  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  resources :items do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end

  resources :tweets

  # ActiveAdmin.routes(self)
  # devise_for :users
  # as :user do
  #   get "signin", to: 'devise/sessions#new'
  #   delete "signout", to: 'devise/sessions#destroy'
  #   get "signup", to: 'devise/registrations#new'
  # end
  # get 'pages/home'
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact_us', to: 'pages#contact_us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# class User < ApplicationRecord
#   # Include default devise modules. Others available are:
#   # :confirmable, :lockable, :timeoutable and :omniauthable
#   devise :database_authenticatable, :registerable,
#          :recoverable, :rememberable, :trackable, :validatable
# end

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :items

  validates :username, presence: true, uniqueness: true, length: { minimum: 6}
  validates :name, presence: true

  acts_as_followable
  acts_as_follower

  acts_as_voter
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    @tweets = @user.tweets
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<!-- <div class="container">
  <h1><%= @user.username %></h1>
  <p><%= @user.name %></p>
</div> -->


<div class="container">


  <div class="row">
      <div class="col-md-4">
        <% if user_signed_in? %>
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= @user.username %></h5>
              <p class="card-text"><%= @user.name %></p>
              <% if current_user.following?(@user) %>
                <p class="card-text"><%= link_to "UnFollow", unfollow_user_path(@user.username), method: :delete %></p>
              <% else %>
                <p class="card-text"><%= link_to "Follow", follow_user_path(@user.username), method: :post %></p>
              <% end %>
            </div>
          </div>
        <% else %>
          <p> Please sign up to post tweets! </p>
        <% end %>
      </div>
      <div class="col-md-8">


          <ul class="list-group">
              <% @tweets.each do |tweet| %>

                  <%= link_to tweet, class: "list-group-item list-group-item-action" do %>

                      <h5><%= tweet.user.username %></h5>

                    <p><%= tweet.content %></p>
                      <small>
                        <% if tweet.user == current_user %>
                          <%= link_to 'Edit', edit_tweet_path(tweet) %>
                          <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
                        <% end %>
                      </small>
                  <% end %>

              <% end %>
          </ul>

    </div>
  </div>
</div>